# Generated by Django 4.2.5 on 2023-09-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myphoto',
            name='upload_datetime',
        ),
        migrations.AddField(
            model_name='myphoto',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='yuklangan sana'),
        ),
    ]
