# Generated by Django 4.2.5 on 2023-09-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_myphoto_upload_datetime_myphoto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphoto',
            name='image',
            field=models.URLField(verbose_name="rasmning url'i"),
        ),
    ]
